name = "StructMapping"
uuid = "7c3b921d-20d6-4eba-ad57-605525e86ab2"
authors = ["matsueushi <matsueushi@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1"
