name = "StructMapping"
uuid = "7c3b921d-20d6-4eba-ad57-605525e86ab2"
authors = ["matsueushi <matsueushi@gmail.com>"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
